"""add_airline_events

Revision ID: 0a4badec8d02
Revises: a1c3e5f7b9d2
Create Date: 2026-09-09 10:42:24.988931

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4badec8d02'
down_revision: str | Sequence[str] | None = 'a1c3e5f7b9d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('discount_info', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airline_events')),
    sa.UniqueConstraint('source', 'external_id', name='uq_airline_events_source_ext')
    )
    op.create_index('ix_airline_events_fetched', 'airline_events', ['fetched_at'], unique=False)
    op.create_index('ix_airline_events_source', 'airline_events', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_airline_events_source', table_name='airline_events')
    op.drop_index('ix_airline_events_fetched', table_name='airline_events')
    op.drop_table('airline_events')
    # ### end Alembic commands ###
