"""offers and price_snapshots

Revision ID: 4b8aa7303d5c
Revises: 63a9d4c63b8f
Create Date: 2026-09-01 19:53:45.129299

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b8aa7303d5c"
down_revision: str | Sequence[str] | None = "63a9d4c63b8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("watch_id", sa.UUID(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("min_price_krw", sa.Integer(), nullable=False),
        sa.Column("median_price_krw", sa.Integer(), nullable=True),
        sa.Column("offer_count", sa.Integer(), nullable=True),
        sa.Column("best_offer_id", sa.UUID(), nullable=True),
        sa.Column("coverage_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("live_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("credits_used", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["watch_id"],
            ["watches.id"],
            name=op.f("fk_price_snapshots_watch_id_watches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_snapshots")),
    )
    op.create_index(
        "ix_snapshots_watch_captured", "price_snapshots", ["watch_id", "captured_at"], unique=False
    )
    op.create_table(
        "offers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("watch_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("price_krw", sa.Integer(), nullable=False),
        sa.Column("price_original", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency_original", sa.Text(), nullable=True),
        sa.Column("depart_date", sa.Date(), nullable=True),
        sa.Column("return_date", sa.Date(), nullable=True),
        sa.Column("carrier", sa.Text(), nullable=True),
        sa.Column("deep_link", sa.Text(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("freshness", sa.Text(), nullable=False),
        sa.Column("cache_age_days", sa.Integer(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("verify_run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["watch_runs.id"],
            name=op.f("fk_offers_run_id_watch_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["watch_id"],
            ["watches.id"],
            name=op.f("fk_offers_watch_id_watches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offers")),
        sa.UniqueConstraint(
            "watch_id", "run_id", "source", "external_id", name="uq_offers_watch_run_source_ext"
        ),
    )
    op.create_index(
        "ix_offers_watch_collected", "offers", ["watch_id", "collected_at"], unique=False
    )
    op.create_index("ix_offers_watch_price", "offers", ["watch_id", "price_krw"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_offers_watch_price", table_name="offers")
    op.drop_index("ix_offers_watch_collected", table_name="offers")
    op.drop_table("offers")
    op.drop_index("ix_snapshots_watch_captured", table_name="price_snapshots")
    op.drop_table("price_snapshots")
    # ### end Alembic commands ###
