"""watches and watch_runs

Revision ID: 63a9d4c63b8f
Revises: b4f12a9ec812
Create Date: 2026-09-01 16:03:35.349988

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63a9d4c63b8f'
down_revision: str | Sequence[str] | None = 'b4f12a9ec812'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interval_min', sa.Integer(), server_default=sa.text('360'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sampled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination', sa.Text(), sa.Computed("params->>'destination'", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watches'))
    )
    op.create_index('ix_watches_destination', 'watches', ['destination'], unique=False)
    op.create_index('ix_watches_status_next_run', 'watches', ['status', 'next_run_at'], unique=False)
    op.create_table('watch_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watch_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('sources_ok', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('sources_failed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('offers_found', sa.Integer(), nullable=True),
    sa.Column('best_price_krw', sa.Integer(), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], name=op.f('fk_watch_runs_watch_id_watches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watch_runs'))
    )
    op.create_index('ix_watch_runs_watch_started', 'watch_runs', ['watch_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watch_runs_watch_started', table_name='watch_runs')
    op.drop_table('watch_runs')
    op.drop_index('ix_watches_status_next_run', table_name='watches')
    op.drop_index('ix_watches_destination', table_name='watches')
    op.drop_table('watches')
    # ### end Alembic commands ###
