"""source layer tables

Revision ID: 8e15245760f8
Revises: 383dcf6b47f1
Create Date: 2026-09-01 20:29:56.483493

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e15245760f8"
down_revision: str | Sequence[str] | None = "383dcf6b47f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "call_budgets",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("sample_cap", sa.Integer(), nullable=False),
        sa.Column("used_verify", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("used_sample", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sample_day", sa.Date(), nullable=True),
        sa.Column("used_sample_day", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source", "period_start", name=op.f("pk_call_budgets")),
    )
    op.create_table(
        "fx_rates",
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("rate_krw", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("currency", "rate_date", name=op.f("pk_fx_rates")),
    )
    op.create_table(
        "places",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=True),
        sa.Column("area_code", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_places")),
        sa.UniqueConstraint("source", "external_id", name="uq_places_source_ext"),
    )
    op.create_table(
        "probe_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("watch_id", sa.UUID(), nullable=False),
        sa.Column("depart_date", sa.Date(), nullable=False),
        sa.Column("nights", sa.Integer(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column("hit", sa.Boolean(), nullable=False),
        sa.Column("price_krw", sa.Integer(), nullable=True),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_probe_log")),
    )
    op.create_index("ix_probe_log_created", "probe_log", ["created_at"], unique=False)
    op.create_table(
        "source_health",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=True),
        sa.Column("last_ok_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("disabled_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("source", name=op.f("pk_source_health")),
    )
    op.create_table(
        "coverage_cells",
        sa.Column("watch_id", sa.UUID(), nullable=False),
        sa.Column("depart_date", sa.Date(), nullable=False),
        sa.Column("nights", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_price_krw", sa.Integer(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("probe_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_probe_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
        sa.ForeignKeyConstraint(
            ["watch_id"],
            ["watches.id"],
            name=op.f("fk_coverage_cells_watch_id_watches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "watch_id", "depart_date", "nights", name=op.f("pk_coverage_cells")
        ),
    )
    op.create_index(
        "ix_cells_watch_state_probe",
        "coverage_cells",
        ["watch_id", "state", "last_probe_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cells_watch_state_probe", table_name="coverage_cells")
    op.drop_table("coverage_cells")
    op.drop_table("source_health")
    op.drop_index("ix_probe_log_created", table_name="probe_log")
    op.drop_table("probe_log")
    op.drop_table("places")
    op.drop_table("fx_rates")
    op.drop_table("call_budgets")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
